settings:
  title: 'Server Status'
  url: 'https://status-page.eidam.dev'
  logo: logo.svg
  daysInHistogram: 30
  collectResponseTimes: true

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: hub
    name: Velyn Hub
    url: 'https://velyn.my.id/'

  - id: dns
    name: Velyn DNS
    url: 'https://dns.velyn.my.id/'

  - id: shared
    name: Shared Files
    url: 'https://files.velyn.my.id/'

  - id: blog
    name: Blog Velyn
    url: 'https://blog.velyn.my.id/'

  - id: clipboard
    name: Simple Clipboard
    url: 'https://clipboard.velyn.my.id/'

  - id: sankaku
    name: Sankaku Viewer
    url: 'https://sankaku.velyn.my.id/'
